#!/bin/sh

if [ $# -ne 1 ]; then
  >&2 printf 'usage: %s SQLITE_DB\n' "$(basename "$0")"
  exit 1
fi

db=$1

sqlite3 --readonly "$db" <<'END_SQL'
.mode tabs
.headers off
.timeout 5000

select id, code, domain, slug
from CandidateStore
limit 1;
END_SQL

